language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - rbx-18mode
  - ree
  - ruby-head

notifications:
  email:
    - sfgeorge-toadhopper-turtle.testudo12@wronghead.com
  irc:
    channels: "irc.freenode.org#toadhopper"